// <auto-generated />
using System;
using CleanArchitecture.Infrastracture.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Infrastracture.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260113200920_FixSeedingDeterminism")]
    partial class FixSeedingDeterminism
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitecture.Core.Entities.AccountStudentGuardian", b =>
                {
                    b.Property<int>("AccountStudentGuardianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountStudentGuardianID"));

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GuardianID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("AccountStudentGuardianID");

                    b.HasIndex("AccountID");

                    b.HasIndex("GuardianID");

                    b.HasIndex("StudentID");

                    b.ToTable("AccountStudentGuardians");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Accounts", b =>
                {
                    b.Property<Guid>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OpenBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<Guid>("TypeAccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TypeOpenBalance")
                        .HasColumnType("bit");

                    b.HasKey("AccountID");

                    b.HasIndex("TypeAccountID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "007266f8-a4b4-4b9e-a8d2-3e0a6f9df5ec",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33333333-3333-3333-3333-333333333333",
                            Email = "ADMIN@GMAIL.COM",
                            EmailConfirmed = true,
                            Gender = "",
                            HireDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "PASTE_THE_PRECOMPUTED_HASH_HERE",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "22222222-2222-2222-2222-222222222222",
                            TwoFactorEnabled = false,
                            UserName = "ADMIN",
                            UserType = "ADMIN"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Attachments", b =>
                {
                    b.Property<int>("AttachmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentID"));

                    b.Property<string>("AttachmentURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.Property<int?>("VoucherID")
                        .HasColumnType("int")
                        .HasColumnName("VoucherID");

                    b.HasKey("AttachmentID");

                    b.HasIndex("StudentID");

                    b.HasIndex("VoucherID");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageID")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<int?>("TeacherID")
                        .HasColumnType("int");

                    b.Property<int?>("YearID")
                        .HasColumnType("int");

                    b.HasKey("ClassID");

                    b.HasIndex("StageID");

                    b.HasIndex("TeacherID");

                    b.HasIndex("YearID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.CoursePlan", b =>
                {
                    b.Property<int>("YearID")
                        .HasColumnType("int");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<int>("DivisionID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("TermID")
                        .HasColumnType("int");

                    b.HasKey("YearID", "TeacherID", "ClassID", "DivisionID", "SubjectID");

                    b.HasIndex("ClassID");

                    b.HasIndex("DivisionID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("TeacherID");

                    b.HasIndex("TermID");

                    b.ToTable("CoursePlans");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Curriculum", b =>
                {
                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<string>("CurriculumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectID", "ClassID");

                    b.HasIndex("ClassID");

                    b.ToTable("Curriculums");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Division", b =>
                {
                    b.Property<int>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionID"));

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("DivisionID");

                    b.HasIndex("ClassID");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Fee", b =>
                {
                    b.Property<int>("FeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeID"));

                    b.Property<string>("FeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeeNameAlis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("FeeID");

                    b.ToTable("Fees");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.FeeClass", b =>
                {
                    b.Property<int>("FeeClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeClassID"));

                    b.Property<double?>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<int>("FeeID")
                        .HasColumnType("int");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("bit");

                    b.HasKey("FeeClassID");

                    b.HasIndex("ClassID");

                    b.HasIndex("FeeID");

                    b.ToTable("FeeClass");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.GradeType", b =>
                {
                    b.Property<int>("GradeTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeTypeID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxGrade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeTypeID");

                    b.ToTable("GradeTypes");

                    b.HasData(
                        new
                        {
                            GradeTypeID = 1,
                            IsActive = true,
                            MaxGrade = 20m,
                            Name = "Assignments"
                        },
                        new
                        {
                            GradeTypeID = 2,
                            IsActive = true,
                            MaxGrade = 20m,
                            Name = "Attendance"
                        },
                        new
                        {
                            GradeTypeID = 3,
                            IsActive = true,
                            MaxGrade = 10m,
                            Name = "Participation"
                        },
                        new
                        {
                            GradeTypeID = 4,
                            IsActive = true,
                            MaxGrade = 10m,
                            Name = "Oral"
                        },
                        new
                        {
                            GradeTypeID = 5,
                            IsActive = true,
                            MaxGrade = 40m,
                            Name = "Exam"
                        },
                        new
                        {
                            GradeTypeID = 6,
                            IsActive = false,
                            MaxGrade = 20m,
                            Name = "work"
                        },
                        new
                        {
                            GradeTypeID = 7,
                            IsActive = false,
                            MaxGrade = 30m,
                            Name = "lab"
                        },
                        new
                        {
                            GradeTypeID = 8,
                            IsActive = false,
                            MaxGrade = 20m,
                            Name = "skills"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Guardian", b =>
                {
                    b.Property<int>("GuardianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuardianID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuardianDOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GuardianID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Guardians");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Manager", b =>
                {
                    b.Property<int>("ManagerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerID"));

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.Property<int?>("TenantID")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ManagerID");

                    b.HasIndex("SchoolID")
                        .IsUnique();

                    b.HasIndex("TenantID")
                        .IsUnique()
                        .HasFilter("[TenantID] IS NOT NULL");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Month", b =>
                {
                    b.Property<int>("MonthID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MonthID");

                    b.ToTable("Months");

                    b.HasData(
                        new
                        {
                            MonthID = 1,
                            Name = "يناير"
                        },
                        new
                        {
                            MonthID = 2,
                            Name = "فبراير"
                        },
                        new
                        {
                            MonthID = 3,
                            Name = "مارس"
                        },
                        new
                        {
                            MonthID = 4,
                            Name = "أبريل"
                        },
                        new
                        {
                            MonthID = 5,
                            Name = "مايو"
                        },
                        new
                        {
                            MonthID = 6,
                            Name = "يونيو"
                        },
                        new
                        {
                            MonthID = 7,
                            Name = "يوليو"
                        },
                        new
                        {
                            MonthID = 8,
                            Name = "أغسطس"
                        },
                        new
                        {
                            MonthID = 9,
                            Name = "سبتمبر"
                        },
                        new
                        {
                            MonthID = 10,
                            Name = "أكتوبر"
                        },
                        new
                        {
                            MonthID = 11,
                            Name = "نوفمبر"
                        },
                        new
                        {
                            MonthID = 12,
                            Name = "ديسمبر"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.MonthlyGrade", b =>
                {
                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("YearID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("MonthID")
                        .HasColumnType("int");

                    b.Property<int>("GradeTypeID")
                        .HasColumnType("int");

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<int>("TermID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StudentID", "YearID", "SubjectID", "MonthID", "GradeTypeID", "ClassID", "TermID");

                    b.HasIndex("ClassID");

                    b.HasIndex("GradeTypeID");

                    b.HasIndex("MonthID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("TermID");

                    b.HasIndex("YearID");

                    b.HasIndex("StudentID", "SubjectID", "MonthID", "GradeTypeID")
                        .IsUnique();

                    b.ToTable("MonthlyGrades");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("nvarchar(88)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Salary", b =>
                {
                    b.Property<int>("SalaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryID"));

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalaryAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SalaryHireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SalaryMonth")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.HasKey("SalaryID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Salarys");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.School", b =>
                {
                    b.Property<int>("SchoolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolMission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolPhone")
                        .HasColumnType("int");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolVison")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fax")
                        .HasColumnType("int");

                    b.Property<string>("zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolID");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Stage", b =>
                {
                    b.Property<int>("StageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearID")
                        .HasColumnType("int");

                    b.HasKey("StageID");

                    b.HasIndex("YearID");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("DivisionID")
                        .HasColumnType("int");

                    b.Property<int>("GuardianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1012);

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StudentDOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentID");

                    b.HasIndex("DivisionID");

                    b.HasIndex("GuardianID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.StudentClassFees", b =>
                {
                    b.Property<int>("StudentClassFeesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentClassFeesID"));

                    b.Property<decimal?>("AmountDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FeeClassID")
                        .HasColumnType("int");

                    b.Property<bool?>("Mandatory")
                        .HasColumnType("bit");

                    b.Property<string>("NoteDiscount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("StudentClassFeesID");

                    b.HasIndex("FeeClassID");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentClassFees");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectReplacement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerID")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TeacherID");

                    b.HasIndex("ManagerID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Term", b =>
                {
                    b.Property<int>("TermID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TermID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TermID");

                    b.ToTable("Terms");

                    b.HasData(
                        new
                        {
                            TermID = 1,
                            Name = "الأول"
                        },
                        new
                        {
                            TermID = 2,
                            Name = "الثاني"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.TermlyGrade", b =>
                {
                    b.Property<int>("TermlyGradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TermlyGradeID"));

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("TermID")
                        .HasColumnType("int");

                    b.Property<int>("YearID")
                        .HasColumnType("int");

                    b.HasKey("TermlyGradeID");

                    b.HasIndex("ClassID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("TermID");

                    b.HasIndex("YearID");

                    b.HasIndex("StudentID", "TermID", "SubjectID", "ClassID")
                        .IsUnique();

                    b.ToTable("TermlyGrades");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.TypeAccount", b =>
                {
                    b.Property<Guid>("TypeAccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeAccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeAccountID");

                    b.ToTable("TypeAccounts");

                    b.HasData(
                        new
                        {
                            TypeAccountID = new Guid("00000000-0000-0000-0000-000000000001"),
                            TypeAccountName = "Guardain"
                        },
                        new
                        {
                            TypeAccountID = new Guid("00000000-0000-0000-0000-000000000002"),
                            TypeAccountName = "School"
                        },
                        new
                        {
                            TypeAccountID = new Guid("00000000-0000-0000-0000-000000000003"),
                            TypeAccountName = "Branches"
                        },
                        new
                        {
                            TypeAccountID = new Guid("00000000-0000-0000-0000-000000000004"),
                            TypeAccountName = "Funds"
                        },
                        new
                        {
                            TypeAccountID = new Guid("00000000-0000-0000-0000-000000000005"),
                            TypeAccountName = "Employees"
                        },
                        new
                        {
                            TypeAccountID = new Guid("00000000-0000-0000-0000-000000000006"),
                            TypeAccountName = "Banks"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Vouchers", b =>
                {
                    b.Property<int>("VoucherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherID"));

                    b.Property<int>("AccountStudentGuardianID")
                        .HasColumnType("int");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Receipt")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VoucherID");

                    b.HasIndex("AccountStudentGuardianID");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Year", b =>
                {
                    b.Property<int>("YearID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YearID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("YearDateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("YearDateStart")
                        .HasColumnType("datetime2");

                    b.HasKey("YearID");

                    b.HasIndex("SchoolID");

                    b.ToTable("Years");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.YearTermMonth", b =>
                {
                    b.Property<int>("YearID")
                        .HasColumnType("int");

                    b.Property<int>("TermID")
                        .HasColumnType("int");

                    b.Property<int>("MonthID")
                        .HasColumnType("int");

                    b.HasKey("YearID", "TermID", "MonthID");

                    b.HasIndex("MonthID");

                    b.HasIndex("TermID");

                    b.ToTable("YearTermMonths");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "b4b786c9-8b74-446a-8045-c6f1cb38ddca",
                            Name = "ADMIN",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "7cfff771-c7e2-47d9-93be-637dd7ce196c",
                            Name = "MANAGER",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "cfe268b3-dc5f-4834-86e5-5ee4490f8ac2",
                            Name = "STUDENT",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "4",
                            ConcurrencyStamp = "9cc8e7e5-6c33-4a06-b583-6b88853caab6",
                            Name = "TEACHER",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = "5",
                            ConcurrencyStamp = "27ea9fa6-7d68-4ec2-a328-181482d7be65",
                            Name = "GUARDIAN",
                            NormalizedName = "GUARDIAN"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.AccountStudentGuardian", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Accounts", "Accounts")
                        .WithMany("AccountStudentGuardians")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Guardian", "Guardian")
                        .WithMany("AccountStudentGuardians")
                        .HasForeignKey("GuardianID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Student", "Student")
                        .WithMany("AccountStudentGuardians")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Guardian");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Accounts", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.TypeAccount", "TypeAccount")
                        .WithMany("Accounts")
                        .HasForeignKey("TypeAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeAccount");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Attachments", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Student", "Student")
                        .WithMany("Attachments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CleanArchitecture.Core.Entities.Vouchers", "Voucher")
                        .WithMany("Attachments")
                        .HasForeignKey("VoucherID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Student");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Class", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Stage", "Stage")
                        .WithMany("Classes")
                        .HasForeignKey("StageID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CleanArchitecture.Core.Entities.Year", "Year")
                        .WithMany("Classes")
                        .HasForeignKey("YearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Stage");

                    b.Navigation("Teacher");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.CoursePlan", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Class", "Class")
                        .WithMany("CoursePlans")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Division", "Division")
                        .WithMany("CoursePlans")
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Subject", "Subject")
                        .WithMany("CoursePlans")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Teacher", "Teacher")
                        .WithMany("CoursePlans")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Term", "Term")
                        .WithMany("CoursePlans")
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Year", "Year")
                        .WithMany("CoursePlans")
                        .HasForeignKey("YearID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Division");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");

                    b.Navigation("Term");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Curriculum", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Class", "Class")
                        .WithMany("Curriculums")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Subject", "Subject")
                        .WithMany("Curriculums")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Division", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Class", "Class")
                        .WithMany("Divisions")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.FeeClass", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Class", "Class")
                        .WithMany("FeeClasses")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Fee", "Fee")
                        .WithMany("FeeClasses")
                        .HasForeignKey("FeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Fee");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Guardian", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.ApplicationUser", "ApplicationUser")
                        .WithOne("Guardian")
                        .HasForeignKey("CleanArchitecture.Core.Entities.Guardian", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Manager", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.School", "School")
                        .WithOne("Manager")
                        .HasForeignKey("CleanArchitecture.Core.Entities.Manager", "SchoolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Tenant", "Tenant")
                        .WithOne("Manager")
                        .HasForeignKey("CleanArchitecture.Core.Entities.Manager", "TenantID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CleanArchitecture.Core.Entities.ApplicationUser", "ApplicationUser")
                        .WithOne("Manager")
                        .HasForeignKey("CleanArchitecture.Core.Entities.Manager", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CleanArchitecture.Core.Entities.Name", "FullName", b1 =>
                        {
                            b1.Property<int>("ManagerID")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ManagerID");

                            b1.ToTable("Managers");

                            b1.WithOwner()
                                .HasForeignKey("ManagerID");
                        });

                    b.Navigation("ApplicationUser");

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.MonthlyGrade", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Class", "Class")
                        .WithMany("MonthlyGrades")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.GradeType", "GradeType")
                        .WithMany("MonthlyGrades")
                        .HasForeignKey("GradeTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Month", "Month")
                        .WithMany("MonthlyGrades")
                        .HasForeignKey("MonthID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Student", "Student")
                        .WithMany("MonthlyGrades")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Subject", "Subject")
                        .WithMany("MonthlyGrades")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Term", "Term")
                        .WithMany("MonthlyGrades")
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Year", "Year")
                        .WithMany("MonthlyGrades")
                        .HasForeignKey("YearID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("GradeType");

                    b.Navigation("Month");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Term");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Salary", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Teacher", "Teacher")
                        .WithMany("Salaries")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Stage", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Year", "Year")
                        .WithMany("Stages")
                        .HasForeignKey("YearID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Year");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Student", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Division", "Division")
                        .WithMany("Students")
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Guardian", "Guardian")
                        .WithMany("Students")
                        .HasForeignKey("GuardianID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.ApplicationUser", "ApplicationUser")
                        .WithOne("Student")
                        .HasForeignKey("CleanArchitecture.Core.Entities.Student", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CleanArchitecture.Core.Entities.NameAlis", "FullNameAlis", b1 =>
                        {
                            b1.Property<int>("StudentID")
                                .HasColumnType("int");

                            b1.Property<string>("FirstNameEng")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastNameEng")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MiddleNameEng")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StudentID");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentID");
                        });

                    b.OwnsOne("CleanArchitecture.Core.Entities.Name", "FullName", b1 =>
                        {
                            b1.Property<int>("StudentID")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StudentID");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentID");
                        });

                    b.Navigation("ApplicationUser");

                    b.Navigation("Division");

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("FullNameAlis");

                    b.Navigation("Guardian");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.StudentClassFees", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.FeeClass", "FeeClass")
                        .WithMany("StudentClassFees")
                        .HasForeignKey("FeeClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Student", "Student")
                        .WithMany("StudentClassFees")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeeClass");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Teacher", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.ApplicationUser", "ApplicationUser")
                        .WithOne("Teacher")
                        .HasForeignKey("CleanArchitecture.Core.Entities.Teacher", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CleanArchitecture.Core.Entities.Name", "FullName", b1 =>
                        {
                            b1.Property<int>("TeacherID")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TeacherID");

                            b1.ToTable("Teachers");

                            b1.WithOwner()
                                .HasForeignKey("TeacherID");
                        });

                    b.Navigation("ApplicationUser");

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.TermlyGrade", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Class", "Class")
                        .WithMany("TermlyGrades")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Student", "Student")
                        .WithMany("TermlyGrades")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Subject", "Subject")
                        .WithMany("TermlyGrades")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Term", "Term")
                        .WithMany("TermlyGrades")
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Year", "Year")
                        .WithMany("TermlyGrades")
                        .HasForeignKey("YearID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Term");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Vouchers", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.AccountStudentGuardian", "AccountStudentGuardians")
                        .WithMany("Vouchers")
                        .HasForeignKey("AccountStudentGuardianID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountStudentGuardians");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Year", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.School", "School")
                        .WithMany("Years")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.YearTermMonth", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.Month", "Month")
                        .WithMany("YearTermMonths")
                        .HasForeignKey("MonthID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Term", "Term")
                        .WithMany("YearTermMonths")
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Core.Entities.Year", "Year")
                        .WithMany("YearTermMonths")
                        .HasForeignKey("YearID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Month");

                    b.Navigation("Term");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.AccountStudentGuardian", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Accounts", b =>
                {
                    b.Navigation("AccountStudentGuardians");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Guardian");

                    b.Navigation("Manager");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Class", b =>
                {
                    b.Navigation("CoursePlans");

                    b.Navigation("Curriculums");

                    b.Navigation("Divisions");

                    b.Navigation("FeeClasses");

                    b.Navigation("MonthlyGrades");

                    b.Navigation("TermlyGrades");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Division", b =>
                {
                    b.Navigation("CoursePlans");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Fee", b =>
                {
                    b.Navigation("FeeClasses");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.FeeClass", b =>
                {
                    b.Navigation("StudentClassFees");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.GradeType", b =>
                {
                    b.Navigation("MonthlyGrades");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Guardian", b =>
                {
                    b.Navigation("AccountStudentGuardians");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Month", b =>
                {
                    b.Navigation("MonthlyGrades");

                    b.Navigation("YearTermMonths");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.School", b =>
                {
                    b.Navigation("Manager")
                        .IsRequired();

                    b.Navigation("Years");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Stage", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Student", b =>
                {
                    b.Navigation("AccountStudentGuardians");

                    b.Navigation("Attachments");

                    b.Navigation("MonthlyGrades");

                    b.Navigation("StudentClassFees");

                    b.Navigation("TermlyGrades");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Subject", b =>
                {
                    b.Navigation("CoursePlans");

                    b.Navigation("Curriculums");

                    b.Navigation("MonthlyGrades");

                    b.Navigation("TermlyGrades");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Teacher", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("CoursePlans");

                    b.Navigation("Salaries");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Manager")
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Term", b =>
                {
                    b.Navigation("CoursePlans");

                    b.Navigation("MonthlyGrades");

                    b.Navigation("TermlyGrades");

                    b.Navigation("YearTermMonths");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.TypeAccount", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Vouchers", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Year", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("CoursePlans");

                    b.Navigation("MonthlyGrades");

                    b.Navigation("Stages");

                    b.Navigation("TermlyGrades");

                    b.Navigation("YearTermMonths");
                });
#pragma warning restore 612, 618
        }
    }
}
